### ISSUE TITLE
Relative camera pose estimation from 2 images

### ISSUE THREAD

**Issue by KhanhNgoDuy** [dcharatan/flowmap#18]
Hi, I have successfully run the `overfit.py` file with my image folder, which contains 2 images.

However, as I am completely new to SfM and camera estimation, I want to ask how to estimate the relative camera pose of 2 images.

Can you give me some guides on this? Thank you!

**Comment by dcharatan** [comment]
FlowMap saves camera poses to disk in COLMAP format. The first camera pose is always identity, so if you run FlowMap on two images, the second pose will be the relative pose between the two images.

Within the code, [this line](https://github.com/dcharatan/flowmap/blob/19ac72b78d010220bd9487553db4fb463ab317d4/flowmap/overfit.py#L117C5-L117C12) outputs the poses. You can access them via `exports.extrinsics`. These extrinsics are camera-to-world pose matrices in OpenCV format (+Z look vector, +X right vector, -Y up vector). The first one will be identity (a 4x4 identity matrix), and the second one will be the relative pose between the two views. Note that depending on what you're using the poses for, you might have to convert them to a different format (e.g., different look vector, W2C instead of C2W, etc.).

**Comment by KhanhNgoDuy** [comment]
Thank you for your reply. I want to ask further that, given the relative pose, can I calculate the the angular transition from 1 camera view to another (regarding the differences of azimuth, altitude and radius of 2 camera views)?
