### ISSUE TITLE
About focal length and pixel size

### ISSUE THREAD

**Issue by leo-frank** [dcharatan/flowmap#22]
Hi, author! It's really an impressive work! Thanks for your awesome coding.
I have a question about focal length and pixel size.

From [here](https://github.com/dcharatan/flowmap/blob/0254ba4e68ac12de04dca8ee96176836ada3425d/flowmap/model/intrinsics/common.py#L13), it's observed that the pixel size(the actual size of per pixel) is calculated as `1 / (h * w) ** 0.5`, then the f_x of intrinsic matrix is computed as `focal_length / pixel_size`. 
The computation of pixel size is somehow strange for me, can you explain it for me ?

**Comment by dcharatan** [comment]
We do this so that the set of candidate focal lengths (equation 3 in the paper) doesn't depend on the input video's aspect ratio. In other words, we want our candidate focal lengths to yield the same field of view regardless of whether the input video is filmed in portrait or landscape mode.

The alternative would be to make the focal length candidates correspond to fractions of the video's width, for example, but then a landscape video would have very different focal length candidates (as measured by field of view) compared to a portrait video from the same camera.

**Comment by Sissi-lu** [comment]
Hi，

Thank you for your wonderful work. I struggled with the unit of the focal length. I found that the paper's local lengths are between 0.5 and 2 (in resolution-independent units). Does it mean the unit of focal length is mm？ Or is the unit of focal length as pixel?
