### ISSUE TITLE
About results

### ISSUE THREAD

**Issue by wuqun-tju** [dcharatan/flowmap#31]
I ran  the code with default config and changed max_steps.
![image](https://github.com/dcharatan/flowmap/assets/58416153/cfc68f9f-63eb-4eed-8ef1-989c026afdf3)

The command is [python3 -m flowmap.overfit dataset=images dataset.images.root=flowmap_dataset/test3 +experiment=low_memory]
The image is flowmap_dataset that you uploaded. I just choose one set  of images.
This is process:
![image](https://github.com/dcharatan/flowmap/assets/58416153/c01b81fe-f8ab-47e7-b004-9eb2e6514620)
![image](https://github.com/dcharatan/flowmap/assets/58416153/e1210c7e-add8-4d6b-a002-0ae882c7a4a4)

 But  result is bad 
![image](https://github.com/dcharatan/flowmap/assets/58416153/b6a0520c-d845-4ba1-aa7e-27741fd3e634)

Did I miss something? In addition, for lower consuming, I just use 15 frames not 150 frames of [ flowmap_dataset/co3d_bench ]

**Comment by wuqun-tju** [comment]
In addition, for lower consuming, I just use 15 frames not 150 frames of [ flowmap_dataset/co3d_bench ]

**Comment by dcharatan** [comment]
For this scene, you can see the results we got on the bench scene in [Fig. S3 in the supplemental](https://arxiv.org/abs/2404.15259). Here are a few reasons why the results you got might be bad:

- Running on only 15 frames means some points won't be as well constrained, since there are no long-range point tracks to constrain them. If possible, I would recommend running FlowMap on the full sequence instead.
- In general, FlowMap favors smooth depth maps over crisp ones, which is why borders of objects can sometimes have a tearing effect. If you want sharp, high-resolution depth maps, you'll have to fine-tune the depth map at a higher resolution for a large number of steps (say, 10k to 20k). This repo doesn't include code for that, but it should be pretty easy to set up. You would just have to upscale the depth from the CNN at the end of training to initialize a freely optimizable depth map (`nn.Parameter` with HxW shape), then fine-tune that.
- Since FlowMap outputs a depth for every pixel, points that aren't well constrained will show up as noise in the final depth map. Such noisy depth maps work well for 3D Gaussian Splatting initialization, but aren't optimal for other use cases. To get sharp/high-quality depth maps, you could also train 3D Gaussian Splatting (or NeRF) using FlowMap's depth maps/poses as initialization.

@cameronosmith can probably comment on whether any further processing/cropping was applied to the point clouds in Fig. S3. Hope this helps!

**Comment by wuqun-tju** [comment]
Thank you for your reply, I use 150frames to show the result as follow: I think it may be worse than showed in the paper
![image](https://github.com/dcharatan/flowmap/assets/58416153/10770d2a-a7e0-40bb-87d7-2bf96b1eb4c9)
