### ISSUE TITLE
About frames selection

### ISSUE THREAD

**Issue by Guangyun-Xu** [dcharatan/flowmap#36]
Where is the code for selecting frames?

![image](https://github.com/dcharatan/flowmap/assets/38279883/001a375f-3749-46d5-92f6-98cd97ec120f)

**Comment by dcharatan** [comment]
The code is [here](https://github.com/dcharatan/flowmap/blob/main/flowmap/subsample.py). We didn't put a lot of effort into making this a good heuristic for subsampling frames though, so you might find that subsampling uniformly/with a different strategy gives better results. In general, I would recommend inspecting the input to FlowMap to ensure that frames are evenly spaced (in terms of perceived movement/optical flow), since that works best.
