### ISSUE TITLE
How to compute the ATE in the paper? 

### ISSUE THREAD

**Issue by kk6398** [dcharatan/flowmap#47]
How to compute the ATE in the paper?  I didnot find the code to compute the pose error ATE. 

Besides, I find the pose accuracy will decline when the training iteration beyond 3k or 4k. Can you provide some solution?

**Comment by kk6398** [comment]
Hi, sorry, maybe pose accuracy will not decline when the training iteration beyond 3k or 4k.    
Could you provide me some advices that how to compute the ATE?  Is the output of the flowmap extrinsic directly compared （ATE）with the colmap output extrinsic after each iteration?

**Comment by dcharatan** [comment]
The code that computes ATE is [here](https://github.com/dcharatan/flowmap/blob/a6f854fb9376fdaf9c40b2a0cf81a2378424fd84/flowmap/misc/ate.py).

The ATE is computed with respect to the extrinsics provided by the data loader. For real-world data, there are no ground-truth extrinsics, and so the ATE is computed with respect to poses that are known to be reasonable (e.g., COLMAP poses) instead.

There are two reasons why ATE wouldn't necessarily improve beyond 3-4k steps:

1. Since the ATE is computed with respect to poses that aren't really ground truth, past a certain point, improving pose quality won't lower ATE (i.e., the ground truth is inaccurate).
2. The optimization has converged. Since FlowMap uses estimated optical flow, it could theoretically achieve zero loss but not have perfect poses (i.e., FlowMap's results are inaccurate).
