### ISSUE TITLE
Use FlowMap instead of COLMAP

### ISSUE THREAD

**Issue by aeskandari68** [dcharatan/flowmap#8]
Could your code generate a transform matrix that can be used in other Nerf frameworks or methods, such as Nerfstudio or Neuralangelo? These methods require a transform matrix in JSON format for the camera positions of the frame videos. Thanks

**Comment by dcharatan** [comment]
The FlowMap code exports estimated camera poses in COLMAP format, which should be compatible with Nerfstudio's [COLMAP data parser](https://github.com/nerfstudio-project/nerfstudio/blob/main/nerfstudio/data/dataparsers/colmap_dataparser.py). See this code, which is called in `flowmap/overfit.py`, for more details:

https://github.com/dcharatan/flowmap/blob/a6f854fb9376fdaf9c40b2a0cf81a2378424fd84/flowmap/export/colmap.py#L56-L111

If you want to convert to NeRF's `transforms.json` format, you can probably adapt [this script](https://github.com/NVlabs/instant-ngp/blob/master/scripts/colmap2nerf.py). Since it looks like it expects COLMAP datasets to be in `.txt` format, you would have to modify FlowMap to output its COLMAP data in `.txt` format instead of `.bin` format [here](https://github.com/dcharatan/flowmap/blob/a6f854fb9376fdaf9c40b2a0cf81a2378424fd84/flowmap/export/colmap.py#L214).

**Comment by kk6398** [comment]
Hi, I have a question:
    In **export_to_colmap()**, we write the cameras.bin through  (h_uncropped, w_uncropped), and multiply the original height and width respectly in **write_colmap_model()**.  
    And then we unproject the point clouds through the "_uncropped_ intrinsics", "_cropped_ images", and "_cropped_ depths". Is this corrected??   The scale between intrinsics and images, depths   is different.
